### PR TITLE
safail changes

### PR DESCRIPTION
**Pull request by Safailaliyev**
check my code

### CODE REVIEW

**Comment by JuliGV** [comment]
I think, you need add more lines of code)

**Review by IsmailDursun — APPROVED** [review]
keep up the good work

**Comment by frankSerrano07** [comment]
good job bro ...

**Review by IsmailDursun — APPROVED** [review]
approved

**Comment by Shefeg-7** [comment]
Great work Safail

**Comment by Nazakat2335** [comment]
perfect job

**Comment by frankSerrano07** [comment]
approved

**Pull request merged**
